### ISSUE TITLE
Init StatusFinder Failed! Retry after 3 seconds

### ISSUE THREAD

**Issue by ghost** [KedamaOvO/RealTimePPDisplayer#10]
It can detect osu!, the PP counter shows up but it is stuck at 0pp 0x100 0x50 0xMiss.
![bandicam 2018-02-21 22-01-44-372](https://user-images.githubusercontent.com/36701773/36484008-d50e20a8-1752-11e8-856b-0a160ad39378.jpg)

**Comment by KedamaOvO** [comment]
try install .net framework 4.6

**Comment by ghost** [comment]
I have the latest version of .NET Framework (4.6.2) and this error still appears.

**Comment by KedamaOvO** [comment]
Your system is win7?
If it is I will try to reproduce this problem in windows 7 environment.
Because I found this problem seems to only appear in windowd 7.

**Comment by GarrettSchuetz** [comment]
I have the same problem on Windows 10
Edit: After doing nothing, 25 minutes later the Init BeatmapFinder worked but the PPShow window didn't launch

**Comment by KedamaOvO** [comment]
@GarrettSchuetz
Try entering the command "**rtpp add wpf**".
If no PPShow, you probably do not have RealTimePPDisplayer installed.
If PPShow is show, then OutputMethods in config.ini does not have wpf.

**Comment by GarrettSchuetz** [comment]
These are my logs. Even though I unzipped the RealTimePPDisplayer to the Sync folder, it doesn't seem to install anymore
[Log 1](https://imgur.com/xzBviix)
Also when I tried to install it, it gave me this message
[Log 2](https://imgur.com/TAryFOm)

**Comment by KedamaOvO** [comment]
Please download from github in browser.
Github now mandates TLS1.2, So Sync can not download plugins.
Download these two files and then extract to the Sync folder
https://github.com/KedamaOvO/OsuRTDataProvider-Release/releases/download/v1.3.3/OsuRTDataProvider-1.3.3.zip
https://github.com/KedamaOvO/RealTimePPDisplayer/releases/download/v1.3.2/RealTimePPDisplayer-1.3.2.zip

**Comment by GarrettSchuetz** [comment]
Ah okay I didn't know that. Downloading those files made it start working again, thank you!

**Comment by kj415j45** [comment]
TLS 1.2 issue would be fixed in future version of Sync ¯\\\_(ツ)\_/¯

**Comment by TheMatrixLP** [comment]
@KedamaOvO @Deliay Init StatusFinder error appears to occur on win 7 ultimate.
Can you confirm? @plezhelp ( r u on win 7 ultimate sp1? )

**Comment by contentdev1** [comment]
the problem has been fixed but it does not display correct pp and only stays at 0pp
