### ISSUE TITLE
can u help me

### ISSUE THREAD

**Issue by ShonGur-Old** [KedamaOvO/RealTimePPDisplayer#15]
Just call me on discord or skype please or tell me what to do, I downloaded it and its in my desktop as a .zip folder I tried putting it into osu! but no luck

**Comment by KedamaOvO** [comment]
This is a Sync plug-in. You also need a [Sync](https://github.com/OsuSync/Sync/releases) program.

Thread: [RTPP Displayer -  display real-time (std/taiko/mania) pp!](https://osu.ppy.sh/community/forums/topics/685031)
Packaged: [Sync+Some Plug-in](https://puu.sh/AmvBJ/7b8bb2c55e.7z)
