### ISSUE TITLE
Instant Crash

### ISSUE THREAD

**Issue by jwok3327** [KedamaOvO/RealTimePPDisplayer#17]
Whenever I try to open Sync.exe, I get this long error message and it crashes seconds after

What does it mean and how do I fix it? It also happens when I have osu! open, and I have installed both plugins

![image](https://user-images.githubusercontent.com/40817393/42258506-196aeb0c-7f2a-11e8-8cb2-6fe8a97940ed.png)

**Comment by KedamaOvO** [comment]
Please check if there are two sync.exe processes in the task manager.

**Comment by jwok3327** [comment]
There were two sync processes, one being in the background
Stopped that one and it works just fine now.
Thanks!
