### ISSUE TITLE
Tried installing the pp displayer with this error popping up.

### ISSUE THREAD

**Issue by Yurismm** [KedamaOvO/RealTimePPDisplayer#20]
![image](https://user-images.githubusercontent.com/40805624/47258713-f5462d00-d496-11e8-8bb0-a275e3f66949.png)

**Comment by Sanekor** [comment]
Same problem

**Comment by MikiraSora** [comment]
please download latest [ortdp](https://github.com/OsuSync/OsuRTDataProvider-Release/releases) plugin and extract to Sync folder.

or type 'plugins install provider' in Sync

**Comment by KedamaOvO** [comment]
This bug was fixed in 1.6.2.
