### ISSUE TITLE
Changing settings in config not showing in game

### ISSUE THREAD

**Issue by V5AUG** [KedamaOvO/RealTimePPDisplayer#22]
When I change the text settings, such as font size, in config, it doesn't show in game

**Comment by MikiraSora** [comment]
If you are using IngameOverlay plugins to show your pp in osu! so you have to setup in IngameOverlay settings.
![image](https://user-images.githubusercontent.com/7549173/49334987-94c21800-f61e-11e8-8814-1ba2e6c69a47.png)
text settings in RTPP config.ini is for RTPP window. like this
![image](https://user-images.githubusercontent.com/7549173/49334993-caff9780-f61e-11e8-9862-373e0624d05e.png)
