### ISSUE TITLE
PP displayer only gives 0.00pp

### ISSUE THREAD

**Issue by Xsenion** [KedamaOvO/RealTimePPDisplayer#23]
I've updated and made sure I'm using everthing up to date. 
Whenever I play a song, without using mods. The displayer will show misses, 100's and 50's but not the pp.
However if I put on a mod (seems to work with any mod), say Hardcore. It'll start working like it should, but only as long as I keep hardcore or any other mod on.

**Comment by KedamaOvO** [comment]
This bug was fixed in 1.6.3
