### ISSUE TITLE
Add the accuracy as a displayable variable

### ISSUE THREAD

**Issue by Tbotas** [KedamaOvO/RealTimePPDisplayer#24]
Hello.
The accuracy is at the moment not a variable accessible for the displayer and it would be useful to have it for certains calculation, for exemple the number of droplet missed in osu!catch could be deduced from that variable. 
Thank you.

**Comment by MikiraSora** [comment]
![image](https://user-images.githubusercontent.com/7549173/51424870-d890d100-1c0e-11e9-9295-90b162392809.png)
It had implemented already.

**Comment by Tbotas** [comment]
Hello.
I know it is possible to calculate it.
The problem is, in osu!catch you cannot do that because you need the number of "droplets" you missed.
The number of fruit catched is n300 and the number of "geki" catched is n100 and the number of "droplet" catched is n50, both the fruits and geki count as a miss when missed so we can use nmiss, but the number of "droplet" missed is unknown.

Thus we either need the accuracy as a variable to calculate the number of droplet missed, or the number of droplet missed to calculate the accuracy.

Thank you.

**Comment by KedamaOvO** [comment]
STD ACC   : (n50 * 50 + n100 * 100 + n300 * 300) / ((n300 + n100 + n50 + nmiss)*300)
 Taiko ACC : (n150 * 150 + n300 *300) / (n300 + n150 + nmiss)
   CTB ACC : (n50 + n100 + n300) / (n50 + n100 + n300 + nmiss + nkatu)
Mania ACC: ((n300 + ngeki) * 300 + nkatu * 200 + n100 * 100 + n50 * 50)/((n300 + ngeki + nkatu + n100 + n50 + nmiss) * 300)
