### ISSUE TITLE
In mania mode with mmf mode,PP obs and my program showed was 0.Other mode was right.By the way,I want to calculate pp of catch,but it told me "Please download ctb-server to sync root dir"

### ISSUE THREAD

**Issue by Someone999** [KedamaOvO/RealTimePPDisplayer#25]

**Comment by KedamaOvO** [comment]
Mania's pp calculation only support mania beatmap.

CTB's pp calculation needs to download [this](https://github.com/OsuSync/RealTimePPDisplayer/releases/download/v1.5.0/ctb-server.7z) and extract it to the sync directory. 
![](https://i.imgur.com/J05DzlH.png)
