### ISSUE TITLE
RealTimePPDisplayer v1.7.0 (3.1.1) & IngameOverlay v0.2.4 Hit Count Format problem

### ISSUE THREAD

**Issue by c4p741nth** [KedamaOvO/RealTimePPDisplayer#29]
My Hit Count Format
![gRv9bIDyYL](https://user-images.githubusercontent.com/49807971/56455267-7454e900-6386-11e9-920d-eeb4ad0ff3ea.png)

but...IngameOverlay display like this
![screenshot064](https://user-images.githubusercontent.com/49807971/56455275-89ca1300-6386-11e9-8526-3c473a63ed46.png)

**Comment by MikiraSora** [comment]
Could you provide your config.ini file and I can take a test.

**Comment by KedamaOvO** [comment]
Thanks for the report, this is a bug, I have fixed it in 1.7.1.
