### ISSUE TITLE
EntryPointNotFoundException:无法在oppai.dll找到名为”get_ppv2“的入口点 when play Taiko,I also can not find it with GetProcAddress in C++,Am I downloaded a wrong  or a corrupted file

### ISSUE THREAD

**Issue by Someone999** [KedamaOvO/RealTimePPDisplayer#33]

**Comment by Someone999** [comment]
Now when play all the mode will occur this

**Comment by Someone999** [comment]
It's solved after restart Sync , I don't know why.

**Comment by MikiraSora** [comment]
make sure oppai.dll version is above RTPP required.
![image](https://user-images.githubusercontent.com/7549173/56653626-9c16ba80-66c0-11e9-8d25-1ee5b274c8dc.png)

**Comment by Someone999** [comment]
Sometimes work , but sometimes not

**Comment by Someone999** [comment]
![image](https://user-images.githubusercontent.com/45456778/56665970-a5625000-66dd-11e9-99ec-dc21b7827fac.png)
and this

**Comment by Someone999** [comment]
![批注 2019-04-24 220926](https://user-images.githubusercontent.com/45456778/56666100-df335680-66dd-11e9-8405-7e53b8e8e4a0.jpg)

**Comment by Someone999** [comment]
This oppai.dll is one of file in the zip of RTPPD 1.7.2

**Comment by KedamaOvO** [comment]
It seems that your RTPPD version is lower than 1.6.8. And after 1.6.8, RTPPD changed to oppai-ng's ezpp API. You can replace oppai.dll by yourself.

> Sometimes work , but sometimes not

It may be that you have two different versions of RTPPD in Plugins folder.

**Comment by Someone999** [comment]
I found it just now , the RTPPD I take in folder is lower version , because of the older source code. I want to get info of stars , so add code into the plugin code , but I didn't notice the version of the RTPPD.

**Comment by Someone999** [comment]
By the way , why ezpp can not calculate the info of Mania Beatmap.

**Comment by KedamaOvO** [comment]
oppai can only calcuate std and taiko.

**Comment by Someone999** [comment]
I see. So , could you make the Stars to be a accessable variable? Now I can only output variable "_beatmapStars" to a file to get Mania stars, and use Ezpp to get std stars.(I rarely play Taiko)

**Comment by KedamaOvO** [comment]
> I see. So , could you make the Stars to be a accessable variable? Now I can only output variable "_beatmapStars" to a file to get Mania stars, and use Ezpp to get std stars.(I rarely play Taiko)

I have no plans to release a new version for the time being. But you can pull the latest commit and complie. 
I have added "rt_stars" and “stars” in the latest commit.
