### ISSUE TITLE
Ingame Displayer not working somehow?

### ISSUE THREAD

**Issue by Adim2P** [KedamaOvO/RealTimePPDisplayer#34]
I tried injecting the overlay on osu! using the "overlay i" command it said it inject Overlay.dll but it doesn't appear anything in game when I play a map I force path my Osu!exec and my song directory still nothing works, the only thing that works is the obs displayer help for in game?

**Comment by Jakads** [comment]
same here

**Comment by KedamaOvO** [comment]
![image](https://user-images.githubusercontent.com/9410177/57980072-c73ec080-7a58-11e9-895f-2abfaa4e0692.png)

Please check if osu ​​has checked the compatibility mode.
Overlay does not currently support compatibility mode.

**Comment by Adim2P** [comment]
Turned off, idk whats the problem man

**Comment by KedamaOvO** [comment]
try use "o osu"

**Comment by Adim2P** [comment]
Already tried that it said it injected but I don't see any display in game.

**Comment by MikiraSora** [comment]
please provide screenshot of Sync and logs ,  emm
what's "obs displayer help" mean?

**Comment by Adim2P** [comment]
> please provide screenshot of Sync and logs , emm
> what's "obs displayer help" mean?

obs displayer, help*  === I mean the obs displayer works like the pop window box with the chroma key? Yeh that works the in game displayer doesn't, and where can I find this sync and logs?

**Comment by KedamaOvO** [comment]
https://github.com/OsuSync/Sync/issues/69#issuecomment-494459045

**Comment by Adim2P** [comment]
> [OsuSync/Sync#69 (comment)](https://github.com/OsuSync/Sync/issues/69#issuecomment-494459045)

I don't have any variable errors, it injects I can see the dll injected on osu! I used process hacker to see the injected dlls, It just doesn't appear anywhere in game, I'm thinking of xinput1_4.dll as the main cause but I highly it doubt it was a xinput error since it was a JRE only problem when it comes to overlay, I'm using a windows 7 so overlay compatabilities is kinda dissappointing, tho I got mscorelib problems when trying to configure the overlay just by typing "Overlay" it produces a lot of exception error like this.
![Capture](https://user-images.githubusercontent.com/46070408/58306732-13aa4780-7e2f-11e9-90a4-cce9c42a2255.PNG)
You can pretty much see  the injector did its job but theres no such thing popping up in my game

**Comment by KedamaOvO** [comment]
Use the config command to configure the overlay.

**Comment by Adim2P** [comment]
Sync is saying its not an existing command

**Comment by KedamaOvO** [comment]
type "plugins install configgui"

**Comment by Adim2P** [comment]
Even tho I can configure it, it just doesn't appear in game. "o osu"
doesn't work even.

**Comment by KedamaOvO** [comment]
Can you send me the Sync folder?

**Comment by Adim2P** [comment]
The whole sync folder with the config? And the plugins installed?

**Comment by KedamaOvO** [comment]
All.

**Comment by Adim2P** [comment]
Ok, I'll send it to you via mediafire link

**Comment by Jakads** [comment]
![image](https://user-images.githubusercontent.com/16955881/58477211-fad2c680-818d-11e9-81ba-4b509693245a.png)
In my case, Overlay.dll isn't even loaded despite the message.

**Comment by Adim2P** [comment]
Lmfao sync is prolly broken, guess we have to wait for the author to fix
this.

**Comment by KedamaOvO** [comment]
> ![image](https://user-images.githubusercontent.com/16955881/58477211-fad2c680-818d-11e9-81ba-4b509693245a.png)
> In my case, Overlay.dll isn't even loaded despite the message.

[Loader.zip](https://github.com/OsuSync/RealTimePPDisplayer/files/3231136/Loader.zip)

Try this Loader.
