### ISSUE TITLE
wpf OutputMethod: HitCount Not Showing

### ISSUE THREAD

**Issue by Jakads** [KedamaOvO/RealTimePPDisplayer#35]
![image](https://user-images.githubusercontent.com/16955881/57979640-990eb000-7a5b-11e9-9307-17f3972155ab.png) (default text settings)
Installing a fresh one and trying it again doesn't work either

**Comment by KedamaOvO** [comment]
![image](https://user-images.githubusercontent.com/9410177/57980040-349e2180-7a58-11e9-8be2-1cb87fea6eaf.png)
Check if DisplayHitCount is checked.

**Comment by Shimogawa** [comment]
I have the same issue. DisplayHitCount option is checked, but the hit count does not show up.
![image](https://user-images.githubusercontent.com/23229568/58403469-53726880-8095-11e9-9d4e-250482ee6f8b.png)

The plugin works normally in version 0.6.11.

**Comment by Jakads** [comment]
I fixed it by actually **UNCHECKING** the DisplayHitCount
Thank you for the help!

**Comment by KedamaOvO** [comment]
I accidentally wrote the opposite display condition.😅
This bug will be fixed in the next release.
