### ISSUE TITLE
System.NullReferenceException when using

### ISSUE THREAD

**Issue by WtzLAS** [KedamaOvO/RealTimePPDisplayer#37]
![image](https://user-images.githubusercontent.com/16971764/63168880-f8cf2400-c067-11e9-9247-9534520aa4ec.png)

this issue seemed to be fixed on commit 86374ac224232c0b4b143fb1dc3a932999b1a188
but it's never released :(

**Comment by KedamaOvO** [comment]
Update OsuRTDataProvider to 1.4.8. 
https://github.com/OsuSync/OsuRTDataProvider-Release/releases/tag/v1.4.8

This exception is RTPPD did not find Beatmap. 
And if you open RTPPD's Debug Mode mode will trigger a message.(#38 )
