### ISSUE TITLE
Make the 'current_score' variable accessible in Format

### ISSUE THREAD

**Issue by Adrriii** [KedamaOvO/RealTimePPDisplayer#39]
Hello,

I have been trying to implement a feature in the Format tool (Hit Count Format option), that would print the current maximum achievable score in mania.

Even if i cannot get a precise value, it would be cool to at least make an estimate, and I need the current score value for this.

I have been trying to do this using the current judges, but it was way too inconsistent.

**Comment by KedamaOvO** [comment]
added in 1.8.6.
