### ISSUE TITLE
Can't find font path

### ISSUE THREAD

**Issue by JiminKai** [KedamaOvO/RealTimePPDisplayer#43]
Hey!

I'm trying to change my font but it keeps saying "Font path not found! Please enter the font path manually
or try to select another font". If i try to do it manually it says (in osu) "Load font *path* failed! Reset to default font."

Only happens with new installed fonts and not with the fonts that come with windows.
Paint and Photoshop can display them.

Help ಥ_ಥ

**Comment by Yona187** [comment]
still doesnt work... idk why :c
