### ISSUE TITLE
I dont know but nothing works

### ISSUE THREAD

**Issue by luciddOW** [KedamaOvO/RealTimePPDisplayer#45]
I have tried to get this program to work for actually around 2 years this is my first time asking for help I ALWAYS get this error and im no hacker I can fix it.

https://imgur.com/a/1LYNmNI

HELP PLEASE

**Comment by KedamaOvO** [comment]
see https://osu.ppy.sh/community/forums/topics/685031?n=24

**Comment by luciddOW** [comment]
I did it and now the pp counter shows up but It wont count pp; the "realtimeppdisplayer.dll" file was never unblockable for my other tries. I have tried unblocking it it wont work.
