### ISSUE TITLE
My plugin can not get anything from RTPP 1.8.6, other info was getted by ORTDP.

### ISSUE THREAD

**Issue by Someone999** [KedamaOvO/RealTimePPDisplayer#48]
![screenshot2161](https://user-images.githubusercontent.com/45456778/66196971-0601aa00-e6cc-11e9-8df6-babeee69d96f.jpg)

**Comment by KedamaOvO** [comment]
Is there a detailed description?

**Comment by Someone999** [comment]
After I replaced the 1.8.5 with 1.8.6, all the data from DisplayerBase was 0.

**Comment by Someone999** [comment]
I didn't change any setting, but change the 1.8.6 to 1.8.5 this time.
![screenshot2163](https://user-images.githubusercontent.com/45456778/66205313-ae6d3980-e6df-11e9-92ef-286de4ec198d.jpg)

**Comment by Someone999** [comment]
Sync crashed just now. I don't know why.

**Comment by Someone999** [comment]
Restarted and  crashed again just now.

**Comment by KedamaOvO** [comment]
https://github.com/Someone999/OsuTools/blob/710b9306e6c64e377cfbe0388359bd20fb9d3c09/ORTDP/Main/Main.cs#L35
The problem is here.

You should write like this:
```csharp
arp.RegisterDisplayer("my", (id) => {
    d = new ConsoleApp1.RtppdInfo();
    rtppi = (ConsoleApp1.RtppdInfo)d;
    ppinfo = new SyncPPInfo("rtpp", arp,rtppi,this);
});
```
At 1.8.6, Displayer is created when delayed to ProgramReady.
