### ISSUE TITLE
How do I change display option for ingame overlay?

### ISSUE THREAD

**Issue by neoiw** [KedamaOvO/RealTimePPDisplayer#50]
I tried changing rtpp-multi-output-config.json for better visibility of rtpp-hit-part into 

"format": "${n100@0}x 100 | ${n50@0}x 50 | ${nmiss@0}x Miss"

but if I try to save the change through configgui, it resets back to default.

**Comment by KedamaOvO** [comment]
If you use ConfigGUI to configure sync, you better not edit the configuration file while sync is running.

**Comment by neoiw** [comment]
Oh thanks :) I tried changing it without osu on and it worked.
