### ISSUE TITLE
NaNpp (NaN pp/s)

### ISSUE THREAD

**Issue by c4p741nth** [KedamaOvO/RealTimePPDisplayer#51]
![ภาพ](https://user-images.githubusercontent.com/49807971/71540170-ad177a00-2979-11ea-872e-62702ef530e3.png)
![screenshot049](https://user-images.githubusercontent.com/49807971/71540184-c5879480-2979-11ea-87c3-6f9ef897df53.jpg)

osu! version : b20191227.3
RTPPD version : 1.8.7

**Comment by MikiraSora** [comment]
type 'config' in Sync and set debug mode as true for RTPP&ORTDP plugin.
They will output more message.

**Comment by c4p741nth** [comment]
After I update ORTDP to version 1.5.10 problem solved
