### ISSUE TITLE
pp position command repeatedly

### ISSUE THREAD

**Issue by c4p741nth** [KedamaOvO/RealTimePPDisplayer#53]
![ภาพ](https://user-images.githubusercontent.com/49807971/71582240-d08a2280-2b3b-11ea-8783-a87ed4183b62.png)

**Comment by KedamaOvO** [comment]
sorry, This is a feature in development. Please update [ORTDP](https://github.com/OsuSync/OsuRTDataProvider/releases/download/v1.5.11/OsuRTDataProvider-1.5.11.zip) and forget it.😅
