### ISSUE TITLE
I can not get Stars from BeatmapTuple.Stars.

### ISSUE THREAD

**Issue by Someone999** [KedamaOvO/RealTimePPDisplayer#54]
[osuTools.zip](https://github.com/OsuSync/RealTimePPDisplayer/files/4027826/osuTools.zip)
At \ORTDP\Events.cs line 188->\Beatmaps\Classes.cs line 462

**Comment by Someone999** [comment]
Dependencies are included in \bin\Debug

**Comment by KedamaOvO** [comment]
you need register osuTools.RtppdInfo.
```csharp
RtppdInfo rt = new RtppdInfo();//no call RegisterDisplayer
...
stars = rt.BeatmapTuple.Stars;
```

**Comment by Someone999** [comment]
Thanks. I tought I initialized RtppdInfo at global.
