### ISSUE TITLE
No found beatmap! Make sure the Songs path is correct. Verison:b20200111.3

### ISSUE THREAD

**Issue by cyperdark** [KedamaOvO/RealTimePPDisplayer#55]
![Sync_dqocuw09MZ](https://user-images.githubusercontent.com/21735205/72208088-712ff900-34d1-11ea-96dc-549fc4dc6374.png)

**Comment by KedamaOvO** [comment]
update OsuRTDataProvider to v1.5.12
https://github.com/OsuSync/OsuRTDataProvider/releases
