### ISSUE TITLE
System MissingMethodException

### ISSUE THREAD

**Issue by ZeroRam** [KedamaOvO/RealTimePPDisplayer#56]
After I open Sync and osu!,the message shown an issue with the OsuRTDataProvider, I tried many times to reinstall the OsuRTData,but useless
The pp calculator doesn't work, How can I fix this problem?
here is the log.
[Log-2020-01-14@11.51.55.txt](https://github.com/OsuSync/RealTimePPDisplayer/files/4063431/Log-2020-01-14%4011.51.55.txt)

i need help !!

**Comment by KedamaOvO** [comment]
Update .net framework to 4.6

**Comment by ZeroRam** [comment]
![ne](https://user-images.githubusercontent.com/57694397/72412613-04b03680-372b-11ea-9e8d-ff1d998db7e4.png)
i have the version 4.8 and doesnt let me go back to 4.6 version.

**Comment by KedamaOvO** [comment]
Try Update OsuLiveStatusPanel to latest.
use "plugins update live"

**Comment by ZeroRam** [comment]
thanks for everything, now is working <3
