### ISSUE TITLE
0.00pp (0.00pp/s) in osu!mania

### ISSUE THREAD

**Issue by c4p741nth** [KedamaOvO/RealTimePPDisplayer#63]
![screenshot143](https://user-images.githubusercontent.com/49807971/87687411-e39ad200-c7af-11ea-91a4-f01d17a412c9.jpg)
![screenshot144](https://user-images.githubusercontent.com/49807971/87687415-e5fd2c00-c7af-11ea-8b31-0d18c2d674a1.jpg)
In osu!standard it work but in mania show 0.00pp

ORTDP: 1.6.3
RTPPD: 1.8.7
IngameOverlay: 0.3.2
OsuLiveStatusPanel: 2.3.2

**Comment by KedamaOvO** [comment]
try update to ORTDP 1.6.4

**Comment by c4p741nth** [comment]
fixed
