### ISSUE TITLE
Sometimes RTPPD does't work. That appears with No Special condition. 

### ISSUE THREAD

**Issue by Someone999** [KedamaOvO/RealTimePPDisplayer#71]
![rtppd 0 error](https://user-images.githubusercontent.com/45456778/96076622-5830fa00-0ee0-11eb-976a-f3866bba4e6b.png)
RTPPD looks like didn't init. and most of the data is zero.
![screenshot4023](https://user-images.githubusercontent.com/45456778/96076774-b6f67380-0ee0-11eb-931a-948886307a67.jpg)

**Comment by Someone999** [comment]
I read beatmap info from osu!.db with md5 provided by ORTDP. If current beatmap has been in the database,  the beatmap info will be correct.

**Comment by Someone999** [comment]
And another issue. If I use beatmaps converted from the beatmap from some other games, RTPPD will fail to parse some of them.

**Comment by Someone999** [comment]
Exception
![image](https://user-images.githubusercontent.com/45456778/96112651-91379180-0f15-11eb-821d-1bbe0995bff8.png)

**Comment by Someone999** [comment]
Maybe this can solve it
![image](https://user-images.githubusercontent.com/45456778/96114165-d957b380-0f17-11eb-9cae-3d56a1cf21e1.png)

**Comment by Someone999** [comment]
![screenshot4038](https://user-images.githubusercontent.com/45456778/96219999-85ea7180-0fba-11eb-881e-749e40fdea82.jpg)
Again today.

**Comment by Someone999** [comment]
![image](https://user-images.githubusercontent.com/45456778/96542696-3b783600-12d5-11eb-8856-4347dfe2486b.png)
now

**Comment by Someone999** [comment]
![screenshot4054](https://user-images.githubusercontent.com/45456778/96542795-71b5b580-12d5-11eb-8499-95b6d02e7312.jpg)
Output in game

**Comment by KedamaOvO** [comment]
try update to 1.6.6
https://github.com/OsuSync/OsuRTDataProvider/releases/tag/v1.6.6

**Comment by Someone999** [comment]
![image](https://user-images.githubusercontent.com/45456778/96689573-270b6a80-13b5-11eb-9ab3-3f21c47c53cb.png)

**Comment by Someone999** [comment]
ORTDP had updated to 1.6.6 before I post this.

**Comment by Someone999** [comment]
Zero or null Data usually appears after I replaced my plugin with a newer or older version. Though RTPPD works before the replacement.

**Comment by Someone999** [comment]
I added output in my plugin at every ORTDP Event I used.There is only one line of output.
![image](https://user-images.githubusercontent.com/45456778/96860082-e8e57800-1494-11eb-8d0d-14a7aef5e09f.png)

**Comment by Someone999** [comment]
I got it. If my plugin enabled debug mode and Sync be restarted, RTPPD will not work.

**Comment by Someone999** [comment]
I need to disable debug mode and restart Sync to make RTPPD work.

**Comment by Someone999** [comment]
I only output Play Mode and Beatmap Info.  Output of PlayMode is no problem.
So the problem may in output of beatmap reader

**Comment by Someone999** [comment]
codes
![codes](https://user-images.githubusercontent.com/45456778/96865833-0b7b8f00-149d-11eb-909c-edbd5cd05bd2.png)

**Comment by Someone999** [comment]
codes
![image](https://user-images.githubusercontent.com/45456778/96868302-6bc00000-14a0-11eb-8771-62c323cb00ee.png)

**Comment by Someone999** [comment]
Read from OsuDB by default.

**Comment by Someone999** [comment]
But I don't know why sometimes rtppd can not find beatmap.

**Comment by Someone999** [comment]
To sum up,issue1: if sync started and my plugin had already enabled debug mode, RTPPD doesn't work
.
issue 2:
Sometimes RTPPD can not find beatmap.

**Comment by Someone999** [comment]
By the way, I can run ctb-server with python.exe but can not run it with pypy3

**Comment by Someone999** [comment]
No problem after the update of osu! yesterday (20201102.5), thanks
