### ISSUE TITLE
I can't see the plugin in the OBS Studio (20.1.3)

### ISSUE THREAD

**Issue by Roblah** [KedamaOvO/RealTimePPDisplayer#8]
I can't see the TextGDIPlusMMF in my OBS Studio, please help.

**Comment by KedamaOvO** [comment]
you need install plugins.
look [this](https://github.com/KedamaOvO/RealTimePPDisplayer/wiki/How-to-setup-obs-plugins-when-you-are-playing-osu!-fullscrren).

**Comment by Roblah** [comment]
I already do, but nothing happen.

**Comment by Roblah** [comment]
http://prntscr.com/ierhjz (btw, I have the OBS in Spanish because I'm from chile.)

**Comment by KedamaOvO** [comment]
Please check the **obs-text-mmf.dll** file exists in obs plug-in directory(**obs-studio/obs-plugins**).

**Comment by Roblah** [comment]
What i need to check?

**Comment by Roblah** [comment]
http://prntscr.com/if5svf

**Comment by KedamaOvO** [comment]
Is your obs version 20.1.3 or later?

**Comment by Roblah** [comment]
my obs is 20.1.3 exactly

**Comment by Roblah** [comment]
http://prntscr.com/if6qb9

**Comment by KedamaOvO** [comment]
run C:\Program Files (x86)\obs-studio\bin\64bit\obs64.exe
Check for the presence of TextGDIPlusMMF.

**Comment by Roblah** [comment]
Still not have TextGDIPlusMMF

**Comment by Roblah** [comment]
I reinstall my OBS and i install the OBS Studio 21.0.1 and nothing.

**Comment by KedamaOvO** [comment]
This may be the reason.
https://prnt.sc/ifey2n
check unblock then extract.

**Comment by Roblah** [comment]
Still not have the TextGDIPlusMMF, rip, at least, you know what is the reason?

**Comment by KedamaOvO** [comment]
idk, but you may be able to give up mmf to use restful.
https://github.com/KedamaOvO/OsuDataDistributeRestful

**Comment by Roblah** [comment]
Ok, im scared, now with restful, i can't see the pp counter in my OBS ( i follow each step in the page )

**Comment by Roblah** [comment]
http://prntscr.com/ig0ri3
http://prntscr.com/ig0rw9
http://prntscr.com/ig0s4k <--- in this i unblock both archives and i move to Sync
http://prntscr.com/ig0ser

and i have a question, i need to open Sync.exe or not? anyways, open or not is not work for me

**Comment by KedamaOvO** [comment]
yes. you need open Sync,ODDR just sends the data to the browser.

checked **Local file**,select {Sync folder}/html/rtpp.html .(I forgot to update the webpage. :cry:)

move OsuDataDistribute-Restful.dll to **Plugins** Folder
and add **restful** to **OutputMethods** in **config** file.

**Comment by KedamaOvO** [comment]
type http://localhost:10800/api/rtppd/pp in browser. 
This can check whether restful is working or not.
(ODDR needs RTPPD)

**Comment by Roblah** [comment]
http://prntscr.com/ig6tfx wut

**Comment by Roblah** [comment]
http://prntscr.com/ig6u06

**Comment by Roblah** [comment]
Now sync is crashing :D

**Comment by KedamaOvO** [comment]
try 0.0.2.
use http://github.mao-yu.net/OsuDataDistributeRestful/rtpp_old.html

**Comment by KedamaOvO** [comment]
or try 0.0.4(need RTPPD [1.3.2](https://github.com/KedamaOvO/RealTimePPDisplayer/releases))

**Comment by Roblah** [comment]
Finally it works thanks
